// import * as Sequelize from 'sequelize';

// import {CorrelationState} from '@process-engine/correlation.contracts';

// export interface ICorrelationAttributes {
//   correlationId: string;
//   processModelHash: string;
//   processModelId: string;
//   processInstanceId: string;
//   // If the correlation entry pertains to a subprocess, this will contain
//   // The ID of the ProcessInstance that started it.
//   parentProcessInstanceId: string;
//   identity: string;
//   state: CorrelationState;
//   error?: string;
//   // This field is auto-generated by sequelize.
//   // Making this property optional will remove the need to for us
//   // to manually declare it in the schema.
//   createdAt?: Date;
//   // Same as createdAt.
//   updatedAt?: Date;
// }

// export type Correlation = Sequelize.Instance<ICorrelationAttributes> & ICorrelationAttributes;

// export function defineCorrelation(sequelize: Sequelize.Sequelize): Sequelize.Model<Correlation, ICorrelationAttributes> {

//   const attributes: SequelizeAttributes<ICorrelationAttributes> = {
//     correlationId: {
//       type: Sequelize.STRING,
//       allowNull: false,
//     },
//     processInstanceId: {
//       type: Sequelize.STRING,
//       allowNull: true,
//     },
//     parentProcessInstanceId: {
//       type: Sequelize.STRING,
//       allowNull: true,
//     },
//     processModelId: {
//       type: Sequelize.STRING,
//       allowNull: true,
//     },
//     identity: {
//       type: Sequelize.TEXT,
//       allowNull: true,
//     },
//     processModelHash: {
//       type: Sequelize.TEXT,
//       allowNull: false,
//     },
//     state: {
//       type: Sequelize.STRING,
//       allowNull: false,
//     },
//     error: {
//       type: Sequelize.TEXT,
//       allowNull: true,
//     },
//   };

//   return sequelize.define<Correlation, ICorrelationAttributes>('Correlation', attributes);
// }

import {AllowNull, Column, CreatedAt, DataType, Model, Table, UpdatedAt} from 'sequelize-typescript';

import {CorrelationState} from '@process-engine/correlation.contracts';

export interface ICorrelationAttributes {
  correlationId: string;
  processModelHash: string;
  processModelId: string;
  processInstanceId: string;
  // If the correlation entry pertains to a subprocess, this will contain
  // The ID of the ProcessInstance that started it.
  parentProcessInstanceId: string;
  identity: string;
  state: CorrelationState;
  error?: string;
  // This field is auto-generated by sequelize.
  // Making this property optional will remove the need to for us
  // to manually declare it in the schema.
  createdAt?: Date;
  // Same as createdAt.
  updatedAt?: Date;
}

@Table
export class Correlation extends Model<Correlation> implements ICorrelationAttributes {

  @Column
  @AllowNull(false)
  public correlationId: string;

  @Column
  public processInstanceId: string;

  @Column
  public processModelId: string;

  @Column({type: DataType.TEXT})
  @AllowNull(false)
  public processModelHash: string;

  @Column(DataType.TEXT)
  public identity: string;

  @Column
  @AllowNull(false)
  public state: CorrelationState;

  @Column(DataType.TEXT)
  @AllowNull(false)
  public error?: string;

  @Column
  public parentProcessInstanceId: string;

  @CreatedAt
  public createdAt?: Date;

  @UpdatedAt
  public updatedAt?: Date;
}
