import * as Sequelize from 'sequelize';

export interface ICorrelationAttributes {
  id: string;
  correlationId: string;
  processModelHash: string;
  processModelId: string;
  processInstanceId: string;
  identity: string;
  // This field is auto-generated by sequelize.
  // Making this property optional will remove the need to for us
  // to manually declare it in the schema.
  createdAt?: Date;
  // Same as createdAt.
  updatedAt?: Date;
}

export type Correlation = Sequelize.Instance<ICorrelationAttributes> & ICorrelationAttributes;

export function defineCorrelation(sequelize: Sequelize.Sequelize): Sequelize.Model<Correlation, ICorrelationAttributes> {

  const attributes: SequelizeAttributes<ICorrelationAttributes> = {
    id: {
      type: Sequelize.UUID,
      primaryKey: true,
      defaultValue: Sequelize.UUIDV4,
    },
    correlationId: {
      type: Sequelize.STRING,
      allowNull: false,
    },
    processInstanceId: {
      type: Sequelize.STRING,
      allowNull: true,
    },
    processModelId: {
      type: Sequelize.STRING,
      allowNull: true,
    },
    identity: {
      type: Sequelize.TEXT,
      allowNull: true,
    },
    processModelHash: {
      type: Sequelize.TEXT,
      allowNull: false,
    },
  };

  return sequelize.define<Correlation, ICorrelationAttributes>('Correlation', attributes);
}
